<?php

namespace Database\Seeders;

use App\Models\GoalTemplate;
use Illuminate\Database\Seeder;

class GoalTemplateSeeder extends Seeder
{
    /**
     * Seed the goal templates.
     */
    public function run(): void
    {
        $templates = [
            // ==================== KIDS TEMPLATES ====================
            [
                'title' => 'Brush teeth every night',
                'description' => 'Build a healthy habit of brushing teeth before bed',
                'emoji' => '🦷',
                'category' => 'health',
                'audience' => 'kids',
                'goal_type' => 'habit',
                'habit_frequency' => 'daily',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'sticker',
                'suggested_check_in_frequency' => 'daily',
                'sort_order' => 1,
            ],
            [
                'title' => 'Read 10 minutes daily',
                'description' => 'Develop a love for reading with just 10 minutes each day',
                'emoji' => '📚',
                'category' => 'learning',
                'audience' => 'kids',
                'goal_type' => 'habit',
                'habit_frequency' => 'daily',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'sticker',
                'suggested_check_in_frequency' => 'daily',
                'sort_order' => 2,
            ],
            [
                'title' => 'Save allowance for something special',
                'description' => 'Learn to save money for a goal you choose',
                'emoji' => '🐷',
                'category' => 'money',
                'audience' => 'kids',
                'goal_type' => 'milestone',
                'milestone_target' => 50,
                'milestone_unit' => 'dollars',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'family_treat',
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 3,
            ],
            [
                'title' => 'Make bed every morning',
                'description' => 'Start the day with a clean and tidy room',
                'emoji' => '🛏️',
                'category' => 'family',
                'audience' => 'kids',
                'goal_type' => 'habit',
                'habit_frequency' => 'daily',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'sticker',
                'suggested_check_in_frequency' => 'daily',
                'sort_order' => 4,
            ],
            [
                'title' => 'Practice kindness',
                'description' => 'Do one kind thing for someone each day',
                'emoji' => '💝',
                'category' => 'personal_growth',
                'audience' => 'kids',
                'goal_type' => 'habit',
                'habit_frequency' => 'daily',
                'suggested_rewards' => false,
                'suggested_check_in_frequency' => 'daily',
                'sort_order' => 5,
            ],
            [
                'title' => 'Learn to ride a bike',
                'description' => 'Master riding a bicycle without training wheels',
                'emoji' => '🚲',
                'category' => 'fun',
                'audience' => 'kids',
                'goal_type' => 'one_time',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'family_treat',
                'sort_order' => 6,
            ],
            [
                'title' => 'Drink 6 glasses of water',
                'description' => 'Stay hydrated by drinking enough water each day',
                'emoji' => '💧',
                'category' => 'health',
                'audience' => 'kids',
                'goal_type' => 'habit',
                'habit_frequency' => 'daily',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'sticker',
                'suggested_check_in_frequency' => 'daily',
                'sort_order' => 7,
            ],
            [
                'title' => 'Learn 5 new words',
                'description' => 'Expand vocabulary by learning new words each week',
                'emoji' => '📝',
                'category' => 'learning',
                'audience' => 'kids',
                'goal_type' => 'milestone',
                'milestone_target' => 5,
                'milestone_unit' => 'words',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'sticker',
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 8,
            ],

            // ==================== TEENS TEMPLATES ====================
            [
                'title' => 'Finish homework before screen time',
                'description' => 'Complete all homework assignments before using devices',
                'emoji' => '📱',
                'category' => 'learning',
                'audience' => 'teens',
                'goal_type' => 'habit',
                'habit_frequency' => 'daily',
                'suggested_rewards' => false,
                'suggested_check_in_frequency' => 'daily',
                'sort_order' => 10,
            ],
            [
                'title' => 'Part-time job savings goal',
                'description' => 'Save a portion of earnings for a big purchase or college',
                'emoji' => '💰',
                'category' => 'money',
                'audience' => 'teens',
                'goal_type' => 'milestone',
                'milestone_target' => 500,
                'milestone_unit' => 'dollars',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'family_treat',
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 11,
            ],
            [
                'title' => 'Exercise 30 minutes daily',
                'description' => 'Stay active with any form of exercise',
                'emoji' => '🏃',
                'category' => 'health',
                'audience' => 'teens',
                'goal_type' => 'habit',
                'habit_frequency' => 'daily',
                'suggested_rewards' => false,
                'suggested_check_in_frequency' => 'daily',
                'sort_order' => 12,
            ],
            [
                'title' => 'Learn a new skill',
                'description' => 'Pick up a new hobby or skill like coding, music, or art',
                'emoji' => '🎨',
                'category' => 'personal_growth',
                'audience' => 'teens',
                'goal_type' => 'one_time',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'custom',
                'sort_order' => 13,
            ],
            [
                'title' => 'Get 8 hours of sleep',
                'description' => 'Maintain a healthy sleep schedule',
                'emoji' => '😴',
                'category' => 'health',
                'audience' => 'teens',
                'goal_type' => 'habit',
                'habit_frequency' => 'daily',
                'suggested_rewards' => false,
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 14,
            ],
            [
                'title' => 'Help with household chores',
                'description' => 'Contribute to the family by helping with chores',
                'emoji' => '🧹',
                'category' => 'family',
                'audience' => 'teens',
                'goal_type' => 'habit',
                'habit_frequency' => 'weekly',
                'suggested_rewards' => false,
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 15,
            ],
            [
                'title' => 'Read 20 books this year',
                'description' => 'Build a reading habit with a yearly goal',
                'emoji' => '📖',
                'category' => 'learning',
                'audience' => 'teens',
                'goal_type' => 'milestone',
                'milestone_target' => 20,
                'milestone_unit' => 'books',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'custom',
                'suggested_check_in_frequency' => 'monthly',
                'sort_order' => 16,
            ],

            // ==================== FAMILY TEMPLATES ====================
            [
                'title' => 'No-screen dinner twice a week',
                'description' => 'Enjoy quality family time without devices during dinner',
                'emoji' => '🍽️',
                'category' => 'family',
                'audience' => 'family',
                'goal_type' => 'habit',
                'habit_frequency' => 'weekly',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'family_treat',
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 20,
            ],
            [
                'title' => 'Monthly family outing',
                'description' => 'Plan and enjoy a fun activity together every month',
                'emoji' => '🎢',
                'category' => 'fun',
                'audience' => 'family',
                'goal_type' => 'habit',
                'habit_frequency' => 'monthly',
                'suggested_rewards' => false,
                'suggested_check_in_frequency' => 'monthly',
                'sort_order' => 21,
            ],
            [
                'title' => 'Sunday planning ritual',
                'description' => 'Gather as a family to plan the week ahead',
                'emoji' => '📅',
                'category' => 'family',
                'audience' => 'family',
                'goal_type' => 'habit',
                'habit_frequency' => 'weekly',
                'suggested_rewards' => false,
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 22,
            ],
            [
                'title' => 'Family game night',
                'description' => 'Weekly board game or card game night together',
                'emoji' => '🎲',
                'category' => 'fun',
                'audience' => 'family',
                'goal_type' => 'habit',
                'habit_frequency' => 'weekly',
                'suggested_rewards' => false,
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 23,
            ],
            [
                'title' => 'Cook a meal together',
                'description' => 'Prepare a family meal as a team once a week',
                'emoji' => '👨‍🍳',
                'category' => 'family',
                'audience' => 'family',
                'goal_type' => 'habit',
                'habit_frequency' => 'weekly',
                'suggested_rewards' => false,
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 24,
            ],
            [
                'title' => 'Family fitness challenge',
                'description' => 'Stay active together with family walks or bike rides',
                'emoji' => '🚴',
                'category' => 'health',
                'audience' => 'family',
                'goal_type' => 'habit',
                'habit_frequency' => 'weekly',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'family_treat',
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 25,
            ],
            [
                'title' => 'Save for a family vacation',
                'description' => 'Work together to save for a special trip',
                'emoji' => '✈️',
                'category' => 'money',
                'audience' => 'family',
                'goal_type' => 'milestone',
                'milestone_target' => 2000,
                'milestone_unit' => 'dollars',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'family_treat',
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 26,
            ],
            [
                'title' => 'Weekend cleanup together',
                'description' => 'Spend 30 minutes as a family tidying the house',
                'emoji' => '🧽',
                'category' => 'family',
                'audience' => 'family',
                'goal_type' => 'habit',
                'habit_frequency' => 'weekly',
                'suggested_rewards' => true,
                'suggested_reward_type' => 'family_treat',
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 27,
            ],

            // ==================== PARENTS TEMPLATES ====================
            [
                'title' => 'Date night monthly',
                'description' => 'Quality time for parents - schedule a date each month',
                'emoji' => '💑',
                'category' => 'family',
                'audience' => 'parents',
                'goal_type' => 'habit',
                'habit_frequency' => 'monthly',
                'suggested_rewards' => false,
                'suggested_check_in_frequency' => 'monthly',
                'sort_order' => 30,
            ],
            [
                'title' => 'Emergency fund goal',
                'description' => 'Build a 3-6 month emergency fund',
                'emoji' => '🏦',
                'category' => 'money',
                'audience' => 'parents',
                'goal_type' => 'milestone',
                'milestone_target' => 10000,
                'milestone_unit' => 'dollars',
                'suggested_check_in_frequency' => 'monthly',
                'sort_order' => 31,
            ],
            [
                'title' => 'Self-care Sunday',
                'description' => 'Take time for yourself each week',
                'emoji' => '🧘',
                'category' => 'health',
                'audience' => 'parents',
                'goal_type' => 'habit',
                'habit_frequency' => 'weekly',
                'suggested_rewards' => false,
                'suggested_check_in_frequency' => 'weekly',
                'sort_order' => 32,
            ],
            [
                'title' => 'Review family budget',
                'description' => 'Monthly review of income and expenses',
                'emoji' => '📊',
                'category' => 'money',
                'audience' => 'parents',
                'goal_type' => 'habit',
                'habit_frequency' => 'monthly',
                'suggested_rewards' => false,
                'suggested_check_in_frequency' => 'monthly',
                'sort_order' => 33,
            ],
        ];

        foreach ($templates as $template) {
            GoalTemplate::updateOrCreate(
                [
                    'title' => $template['title'],
                    'is_system' => true,
                ],
                array_merge($template, [
                    'is_system' => true,
                    'is_active' => true,
                ])
            );
        }

        $this->command->info('Goal templates seeded successfully!');
    }
}
