import flyonui from 'flyonui';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './node_modules/flyonui/dist/js/*.js',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Instrument Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
            },
            colors: {
                // Module-specific accent colors
                'module-family': {
                    50: '#f0fdf4',
                    100: '#dcfce7',
                    200: '#bbf7d0',
                    300: '#86efac',
                    400: '#4ade80',
                    500: '#22c55e',
                    600: '#16a34a',
                    700: '#15803d',
                },
                'module-assets': {
                    50: '#fefce8',
                    100: '#fef9c3',
                    200: '#fef08a',
                    300: '#fde047',
                    400: '#facc15',
                    500: '#eab308',
                    600: '#ca8a04',
                    700: '#a16207',
                },
                'module-documents': {
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                },
                'module-tasks': {
                    50: '#faf5ff',
                    100: '#f3e8ff',
                    200: '#e9d5ff',
                    300: '#d8b4fe',
                    400: '#c084fc',
                    500: '#a855f7',
                    600: '#9333ea',
                    700: '#7e22ce',
                },
                'module-expenses': {
                    50: '#fdf2f8',
                    100: '#fce7f3',
                    200: '#fbcfe8',
                    300: '#f9a8d4',
                    400: '#f472b6',
                    500: '#ec4899',
                    600: '#db2777',
                    700: '#be185d',
                },
            },
        },
    },
    plugins: [
        flyonui,
    ],
    flyonui: {
        themes: [
            {
                light: {
                    "primary": "#7c3aed",
                    "primary-content": "#ffffff",
                    "secondary": "#06b6d4",
                    "secondary-content": "#ffffff",
                    "accent": "#f59e0b",
                    "accent-content": "#ffffff",
                    "neutral": "#374151",
                    "neutral-content": "#f3f4f6",
                    "base-100": "#ffffff",
                    "base-200": "#f8fafc",
                    "base-300": "#e2e8f0",
                    "base-content": "#1e293b",
                    "info": "#3b82f6",
                    "info-content": "#ffffff",
                    "success": "#22c55e",
                    "success-content": "#ffffff",
                    "warning": "#f59e0b",
                    "warning-content": "#ffffff",
                    "error": "#ef4444",
                    "error-content": "#ffffff",
                },
            },
            {
                dark: {
                    "primary": "#a78bfa",
                    "primary-content": "#1e1b4b",
                    "secondary": "#22d3ee",
                    "secondary-content": "#164e63",
                    "accent": "#fbbf24",
                    "accent-content": "#451a03",
                    "neutral": "#1f2937",
                    "neutral-content": "#d1d5db",
                    "base-100": "#0f172a",
                    "base-200": "#1e293b",
                    "base-300": "#334155",
                    "base-content": "#e2e8f0",
                    "info": "#60a5fa",
                    "info-content": "#1e3a5f",
                    "success": "#4ade80",
                    "success-content": "#14532d",
                    "warning": "#fbbf24",
                    "warning-content": "#451a03",
                    "error": "#f87171",
                    "error-content": "#7f1d1d",
                },
            },
        ],
    },
};
